export struct CrewData {
    id: string,
    name: string,
    description: string,
    member-count: int,
    online-count: int,

    avatar: image,
    has-avatar: bool,

    has-stream: bool,
    stream-name: string,

    voice-count: int,
    v0-initials: string, v0-name: string, v0-speaking: bool,
    v1-initials: string, v1-name: string, v1-speaking: bool,
    v2-initials: string, v2-name: string, v2-speaking: bool,
    v3-initials: string, v3-name: string, v3-speaking: bool,

    msg-count: int,
    m0-author: string, m0-text: string,
    m1-author: string, m1-text: string,

    unread-count: int,
    unread-mention: bool,

    sfu-enabled: bool,
}

export struct MemberData {
    id: string,
    name: string,
    initials: string,
    online: bool,
    speaking: bool,
}

export struct ChatMessageData {
    message-id: string,
    sender-id: string,
    sender-name: string,
    sender-initials: string,
    text: string,
    timestamp: string,
    display-time: string,
    is-group-start: bool,
    is-continuation: bool,
    is-system: bool,
    is-gif: bool,
    gif-image: image,
    has-gif-image: bool,
    gif-preview-url: string,
    gif-width: int,
    gif-height: int,
}

export struct GifItemData {
    gif-id: string,
    url: string,
    preview-url: string,
    width: int,
    height: int,
    preview: image,
    has-preview: bool,
}

export struct VoiceChannelMember {
    id: string,
    name: string,
    initials: string,
    speaking: bool,
}

export struct VoiceChannelData {
    id: string,
    name: string,
    member-count: int,
    is-default: bool,
    expanded: bool,
    active: bool,
    members: [VoiceChannelMember],
}

export struct AudioDeviceData {
    id: string,
    name: string,
    is-default: bool,
}

export struct CaptureSourceData {
    id: string,
    name: string,
    mode: string,
    pid: int,
    exe: string,
    is-fullscreen: bool,
    resolution: string,
    thumbnail: image,
    has-thumbnail: bool,
}

export struct DiscoverCrewData {
    id: string,
    name: string,
    description: string,
    member-count: int,
    online-count: int,
    open: bool,
    avatar: image,
    has-avatar: bool,
}

export struct SearchUserData {
    id: string,
    display-name: string,
    is-friend: bool,
}
