export struct CrewData {
    id: string,
    name: string,
    description: string,
    member-count: int,
    online-count: int,

    avatar: image,
    has-avatar: bool,

    has-stream: bool,
    stream-name: string,

    voice-count: int,
    v0-initials: string, v0-name: string, v0-speaking: bool,
    v1-initials: string, v1-name: string, v1-speaking: bool,
    v2-initials: string, v2-name: string, v2-speaking: bool,
    v3-initials: string, v3-name: string, v3-speaking: bool,

    msg-count: int,
    m0-author: string, m0-text: string,
    m1-author: string, m1-text: string,
}

export struct MemberData {
    id: string,
    name: string,
    initials: string,
    online: bool,
    speaking: bool,
}

export struct ChatMessageData {
    sender-name: string,
    text: string,
    timestamp: string,
}

export struct VoiceChannelMember {
    id: string,
    name: string,
    initials: string,
    speaking: bool,
}

export struct VoiceChannelData {
    id: string,
    name: string,
    member-count: int,
    is-default: bool,
    expanded: bool,
    active: bool,
    members: [VoiceChannelMember],
}

export struct AudioDeviceData {
    id: string,
    name: string,
    is-default: bool,
}

export struct DiscoverCrewData {
    id: string,
    name: string,
    description: string,
    member-count: int,
    online-count: int,
    open: bool,
}
