//! Production signup canary.
//!
//! Answers one question on a schedule: **can a brand-new user sign up right
//! now?** Everything else in the suite runs against source; this runs against
//! whatever is actually deployed.
//!
//! It exists because the failure that took signup down could not be caught any
//! other way. `NAKAMA_HTTP_KEY` is baked into the client at build time, while
//! the server's value is generated by Render. When the two drift, the guest
//! `discover_crews` call 401s, the client shows an empty window, and **nothing
//! is recorded anywhere** — the request that fails is the first one a user
//! makes, so there is no session, no error report, and no server-side signal
//! beyond an anonymous 401. Signup can be dead for days while the dashboards
//! look calm.
//!
//! Scheduled and run on deploy, not per-PR: this failure comes from environment
//! drift (a rotated secret, an edited CI secret, a redeploy) and happens with no
//! PR at all. A per-PR run would also be testing the deployed server rather
//! than the PR's code.
//!
//! ## Why this speaks HTTP directly
//!
//! It used to call `mello_core::nakama::NakamaClient`, which reads better but
//! drags in keyring (D-Bus on Linux) and mello-sys, which builds libmello via
//! CMake and vcpkg and downloads ONNX Runtime. That took minutes to build and
//! broke on the Linux runner, which left production monitoring blind for
//! reasons that had nothing to do with production (issue #33). A monitor should
//! have as few reasons to break as the thing it monitors.
//!
//! The cost is that this no longer exercises the real client code path. That is
//! covered instead by `scripts/run-signup-smoke.sh`, which drives the actual
//! built binary through a real signup before each release.
//!
//! Exit code 0 = signup works. Non-zero = it does not.
//!
//! ```text
//! NAKAMA_HTTP_KEY=... NAKAMA_SERVER_KEY=... cargo run -p canary
//! ```

use std::time::{Duration, Instant};

/// Overall budget. A signup path slower than this is broken from a user's point
/// of view even if it eventually succeeds.
const TOTAL_BUDGET: Duration = Duration::from_secs(60);

/// Warn below this many discoverable crews. Onboarding has a Create Crew
/// fallback, so a thin list is not fatal — but it is worth knowing before the
/// funnel bottoms out rather than after.
const THIN_CREW_FUNNEL: usize = 3;

struct Target {
    base: String,
    http_key: String,
    server_key: String,
}

impl Target {
    /// Production by default; `NAKAMA_*` overrides let the same binary check a
    /// local stack.
    fn from_env() -> Self {
        let var = |k: &str, default: &str| {
            std::env::var(k)
                .ok()
                .filter(|v| !v.is_empty())
                .unwrap_or_else(|| default.to_string())
        };

        let host = var("NAKAMA_HOST", "mello-api-1iiv.onrender.com");
        let port = var("NAKAMA_PORT", "443");
        let ssl = !matches!(
            var("NAKAMA_SSL", "true").to_ascii_lowercase().as_str(),
            "0" | "false" | "no" | "off"
        );
        let scheme = if ssl { "https" } else { "http" };

        Self {
            base: format!("{scheme}://{host}:{port}"),
            // These defaults are the same insecure fallbacks the client uses
            // when built without secrets; if they reach production it will
            // reject them, which is the correct outcome.
            http_key: var("NAKAMA_HTTP_KEY", "defaulthttpkey"),
            server_key: var("NAKAMA_SERVER_KEY", "defaultkey"),
        }
    }
}

struct Step {
    name: &'static str,
    detail: String,
    elapsed: Duration,
}

fn main() -> std::process::ExitCode {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();

    let rt = match tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
    {
        Ok(rt) => rt,
        Err(e) => {
            eprintln!("canary: cannot start runtime: {e}");
            return std::process::ExitCode::FAILURE;
        }
    };

    match rt.block_on(async { tokio::time::timeout(TOTAL_BUDGET, run_canary()).await }) {
        Ok(Ok(steps)) => {
            println!("\n✓ signup is working");
            for s in &steps {
                println!(
                    "  {:<28} {:>6}ms  {}",
                    s.name,
                    s.elapsed.as_millis(),
                    s.detail
                );
            }
            std::process::ExitCode::SUCCESS
        }
        Ok(Err(msg)) => {
            eprintln!("\n✗ SIGNUP IS BROKEN: {msg}");
            eprintln!("\nA new user attempting to sign up right now would fail.");
            std::process::ExitCode::FAILURE
        }
        Err(_) => {
            eprintln!(
                "\n✗ SIGNUP IS BROKEN: the flow did not finish within {}s",
                TOTAL_BUDGET.as_secs()
            );
            std::process::ExitCode::FAILURE
        }
    }
}

async fn run_canary() -> Result<Vec<Step>, String> {
    let target = Target::from_env();
    println!("canary → {}", target.base);

    let http = reqwest::Client::builder()
        .timeout(Duration::from_secs(20))
        .build()
        .map_err(|e| format!("cannot build an HTTP client: {e}"))?;

    let mut steps = Vec::new();

    // ---------------------------------------------------------------------
    // 1. Guest crew discovery.
    //
    // The single most important check: the first request a new user makes,
    // authenticated with the http_key rather than a session, and where key
    // drift shows up.
    // ---------------------------------------------------------------------
    let t = Instant::now();
    let resp = http
        .post(format!(
            "{}/v2/rpc/discover_crews?http_key={}",
            target.base, target.http_key
        ))
        .header("Content-Type", "application/json")
        // Nakama takes an RPC payload as a JSON *string*, not an object, so the
        // body is the payload JSON encoded again as a string.
        .json(&serde_json::Value::String("{\"limit\":50}".into()))
        .send()
        .await
        .map_err(|e| format!("guest crew discovery could not reach the server: {e}"))?;

    let status = resp.status();
    let body = resp.text().await.unwrap_or_default();
    if !status.is_success() {
        let hint = if status.as_u16() == 401 {
            " A 401 means NAKAMA_HTTP_KEY no longer matches the server."
        } else {
            ""
        };
        return Err(format!(
            "guest crew discovery returned {status}: {body}. This is the first \
             call a new user makes, authenticated with the http_key rather than \
             a session.{hint}"
        ));
    }

    let crew_count = count_crews(&body);
    steps.push(Step {
        name: "discover_crews (guest)",
        detail: match crew_count {
            Some(n) => format!("{n} crews"),
            None => "responded (shape not recognised)".into(),
        },
        elapsed: t.elapsed(),
    });

    match crew_count {
        Some(0) => eprintln!(
            "  ! warning: discovery succeeded but returned zero crews. New users \
             can only proceed by creating their own."
        ),
        Some(n) if n < THIN_CREW_FUNNEL => eprintln!(
            "  ! warning: only {n} discoverable crews. If these go invite-only or \
             are deleted, new users have nothing to join."
        ),
        _ => {}
    }

    // ---------------------------------------------------------------------
    // 2. Account creation — the actual signup call.
    // ---------------------------------------------------------------------
    let device_id = format!("canary-{:032x}", rand::random::<u128>());
    let t = Instant::now();
    let resp = http
        .post(format!(
            "{}/v2/account/authenticate/device?create=true",
            target.base
        ))
        .basic_auth(&target.server_key, Some(""))
        .json(&serde_json::json!({ "id": device_id }))
        .send()
        .await
        .map_err(|e| format!("account creation could not reach the server: {e}"))?;

    let status = resp.status();
    let body = resp.text().await.unwrap_or_default();
    if !status.is_success() {
        return Err(format!("account creation returned {status}: {body}"));
    }

    let token = serde_json::from_str::<serde_json::Value>(&body)
        .ok()
        .and_then(|v| v.get("token").and_then(|t| t.as_str().map(String::from)))
        .ok_or_else(|| {
            format!("account creation succeeded but returned no session token: {body}")
        })?;
    steps.push(Step {
        name: "authenticate_device",
        detail: "account created".into(),
        elapsed: t.elapsed(),
    });

    // ---------------------------------------------------------------------
    // 3. Session usability. Creating an account is not the same as being able
    //    to use it; onboarding sets the display name immediately after
    //    authenticating, so make the same call it does.
    // ---------------------------------------------------------------------
    let t = Instant::now();
    let resp = http
        .put(format!("{}/v2/account", target.base))
        .bearer_auth(&token)
        .json(&serde_json::json!({ "display_name": "Canary" }))
        .send()
        .await
        .map_err(|e| format!("the new session could not reach the server: {e}"))?;
    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(format!(
            "new account exists but its session is unusable: {status}: {body}"
        ));
    }
    steps.push(Step {
        name: "update_account (auth'd)",
        detail: "session valid".into(),
        elapsed: t.elapsed(),
    });

    // ---------------------------------------------------------------------
    // 4. Clean up, so a run leaves no residue in production. Non-fatal: a
    //    leaked throwaway account matters far less than signup being down, and
    //    failing here would cry wolf.
    // ---------------------------------------------------------------------
    let t = Instant::now();
    match http
        .delete(format!("{}/v2/account", target.base))
        .bearer_auth(&token)
        .send()
        .await
    {
        Ok(r) if r.status().is_success() => steps.push(Step {
            name: "delete_account",
            detail: "cleaned up".into(),
            elapsed: t.elapsed(),
        }),
        Ok(r) => eprintln!(
            "  ! warning: could not delete the canary account ({}); signup itself \
             is fine, but it needs manual removal",
            r.status()
        ),
        Err(e) => eprintln!(
            "  ! warning: could not delete the canary account ({e}); signup itself \
             is fine, but it needs manual removal"
        ),
    }

    // The canary does NOT join a real crew: that would append to a real crew's
    // event ledger and notify real members on every run.

    Ok(steps)
}

/// Count crews in the RPC payload without modelling the whole response.
///
/// Nakama wraps RPC results as `{"payload": "<json string>"}`. Returns `None`
/// if the shape is not what we expect, so a changed response degrades to "no
/// count" rather than a false zero-crew alarm.
fn count_crews(body: &str) -> Option<usize> {
    let outer: serde_json::Value = serde_json::from_str(body).ok()?;
    let payload = outer.get("payload")?.as_str()?;
    let inner: serde_json::Value = serde_json::from_str(payload).ok()?;
    inner
        .get("crews")
        .and_then(|c| c.as_array())
        .map(|a| a.len())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn counts_crews_in_a_wrapped_rpc_payload() {
        let body = r#"{"payload":"{\"crews\":[{\"id\":\"a\"},{\"id\":\"b\"}]}"}"#;
        assert_eq!(count_crews(body), Some(2));
    }

    #[test]
    fn counts_an_empty_crew_list_as_zero() {
        let body = r#"{"payload":"{\"crews\":[]}"}"#;
        assert_eq!(count_crews(body), Some(0));
    }

    /// An unrecognised shape must not read as zero crews, which would raise a
    /// thin-funnel warning that is really a parsing failure.
    #[test]
    fn an_unexpected_shape_yields_no_count() {
        assert_eq!(count_crews("not json"), None);
        assert_eq!(count_crews(r#"{"something":"else"}"#), None);
        assert_eq!(count_crews(r#"{"payload":"{\"other\":1}"}"#), None);
    }
}
