//! Production signup canary.
//!
//! Answers one question on a schedule: **can a brand-new user sign up right
//! now?** Everything else in the test suite runs against source; this runs
//! against whatever is actually deployed.
//!
//! It exists because the failure that took signup down could not be caught any
//! other way. `NAKAMA_HTTP_KEY` is baked into the client at compile time via
//! `option_env!`, while the server's value is generated by Render. When the two
//! drift, the guest `discover_crews` call 401s, the client shows an empty
//! window, and **nothing is recorded anywhere** — the request that fails is the
//! first one a user makes, so there is no session, no error report, and no
//! server-side signal beyond an anonymous 401. Signup can be dead for days
//! while the dashboards look calm.
//!
//! Deliberately triggered on a schedule and on deploy, not per-PR: this class
//! of failure comes from *environment* drift (a rotated secret, an edited CI
//! secret, a redeploy) and happens with no PR at all. A per-PR run would also
//! be testing the deployed server rather than the PR's code.
//!
//! Exit code 0 = signup works. Non-zero = it does not.
//!
//! ```text
//! NAKAMA_HOST=... NAKAMA_HTTP_KEY=... NAKAMA_SERVER_KEY=... cargo run -p canary
//! ```

use std::time::{Duration, Instant};

use mello_core::nakama::client::NakamaClient;
use mello_core::Config;

/// Overall budget. A signup path that takes longer than this is broken from a
/// user's point of view even if it eventually succeeds.
const TOTAL_BUDGET: Duration = Duration::from_secs(60);

struct Step {
    name: &'static str,
    detail: String,
    elapsed: Duration,
}

fn main() -> std::process::ExitCode {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();

    let rt = match tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
    {
        Ok(rt) => rt,
        Err(e) => {
            eprintln!("canary: cannot start runtime: {e}");
            return std::process::ExitCode::FAILURE;
        }
    };

    match rt.block_on(async { tokio::time::timeout(TOTAL_BUDGET, run_canary()).await }) {
        Ok(Ok(steps)) => {
            println!("\n✓ signup is working");
            for s in &steps {
                println!(
                    "  {:<28} {:>6}ms  {}",
                    s.name,
                    s.elapsed.as_millis(),
                    s.detail
                );
            }
            std::process::ExitCode::SUCCESS
        }
        Ok(Err(msg)) => {
            eprintln!("\n✗ SIGNUP IS BROKEN: {msg}");
            eprintln!("\nA new user attempting to sign up right now would fail.");
            std::process::ExitCode::FAILURE
        }
        Err(_) => {
            eprintln!(
                "\n✗ SIGNUP IS BROKEN: the flow did not finish within {}s",
                TOTAL_BUDGET.as_secs()
            );
            std::process::ExitCode::FAILURE
        }
    }
}

/// Production config with `NAKAMA_*` env overrides applied, so the same binary
/// can be pointed at a local stack for development.
fn canary_config() -> Config {
    Config::production().with_env_overrides()
}

async fn run_canary() -> Result<Vec<Step>, String> {
    let cfg = canary_config();
    println!("canary → {}", cfg.http_base());

    let mut steps = Vec::new();
    let mut client = NakamaClient::new(cfg);

    // ---------------------------------------------------------------------
    // 1. Guest crew discovery.
    //
    // The single most important check. This is the first request a new user
    // makes, it authenticates with the compile-time-baked http_key rather than
    // a session, and it is where key drift shows up.
    // ---------------------------------------------------------------------
    let t = Instant::now();
    let (crews, _cursor) = client.discover_crews_public(50, None).await.map_err(|e| {
        format!(
            "guest crew discovery failed: {e}. \
             This is the first call a new user makes and it authenticates with \
             the http_key baked into the client at build time. A 401 here means \
             NAKAMA_HTTP_KEY in the build no longer matches the server."
        )
    })?;
    steps.push(Step {
        name: "discover_crews (guest)",
        detail: format!("{} crews", crews.len()),
        elapsed: t.elapsed(),
    });

    // A successful-but-empty response is its own outage: onboarding step 1
    // has nothing to join. There is now a Create Crew fallback, so this is a
    // warning rather than a hard failure — but it still means the funnel is
    // badly degraded.
    if crews.is_empty() {
        eprintln!(
            "  ! warning: discovery succeeded but returned zero crews. New users \
             can only proceed by creating their own."
        );
    }

    // ---------------------------------------------------------------------
    // 2. Account creation via device auth — the actual signup call.
    // ---------------------------------------------------------------------
    let device_id = format!("canary-{:032x}", rand::random::<u128>());
    let t = Instant::now();
    let (user, created) = client
        .authenticate_device(&device_id)
        .await
        .map_err(|e| format!("account creation failed: {e}"))?;
    if !created {
        return Err(format!(
            "device auth returned an existing account for a freshly random \
             device id ({device_id}) — account creation is not happening"
        ));
    }
    steps.push(Step {
        name: "authenticate_device",
        detail: format!("created user {}", user.id),
        elapsed: t.elapsed(),
    });

    // ---------------------------------------------------------------------
    // 3. Session usability.
    //
    // Creating an account is not the same as being able to use it. Onboarding
    // sets the display name immediately after authenticating, so this makes
    // the same authenticated call the real flow makes next. In production that
    // failure is only logged as a warning, meaning a user can "finish" signup
    // with no display name — so it is worth an explicit check here.
    // ---------------------------------------------------------------------
    let t = Instant::now();
    client
        .update_account_fields(Some("Canary"), None)
        .await
        .map_err(|e| format!("new account exists but its session is unusable: {e}"))?;
    steps.push(Step {
        name: "update_account (auth'd)",
        detail: format!("session valid for {}", user.id),
        elapsed: t.elapsed(),
    });

    // ---------------------------------------------------------------------
    // 4. Clean up. Deliberately last and always attempted, so a canary run
    //    leaves no residue in production. Reported but non-fatal: a leaked
    //    throwaway account is much less serious than signup being down, and
    //    failing the run here would cry wolf.
    // ---------------------------------------------------------------------
    let t = Instant::now();
    match client.delete_account().await {
        Ok(()) => steps.push(Step {
            name: "delete_account",
            detail: "cleaned up".into(),
            elapsed: t.elapsed(),
        }),
        Err(e) => {
            eprintln!(
                "  ! warning: could not delete canary account {}: {e}",
                user.id
            );
            eprintln!("    signup itself is fine; this account needs manual removal.");
        }
    }

    // The canary does NOT join a real crew. Joining would append a
    // member_joined entry to a real crew's event ledger and notify real
    // members, every 30 minutes. The signup-critical path is covered above.

    Ok(steps)
}
