/// Curated emoji dataset for the picker.
/// Each entry: (emoji, name, category_index).
/// Categories: 0=Smileys, 1=People, 2=Nature, 3=Food, 4=Activities, 5=Travel, 6=Objects, 7=Symbols
pub const CATEGORIES: &[&str] = &[
    "Smileys",
    "People",
    "Nature",
    "Food",
    "Activities",
    "Travel",
    "Objects",
    "Symbols",
];

pub struct EmojiEntry {
    pub emoji: &'static str,
    pub name: &'static str,
    pub category: usize,
}

pub fn all_emoji() -> Vec<EmojiEntry> {
    EMOJI_DATA
        .iter()
        .map(|(e, n, c)| EmojiEntry {
            emoji: e,
            name: n,
            category: *c,
        })
        .collect()
}

pub fn search_emoji(query: &str) -> Vec<EmojiEntry> {
    let q = query.to_lowercase();
    EMOJI_DATA
        .iter()
        .filter(|(_, name, _)| name.contains(&q))
        .map(|(e, n, c)| EmojiEntry {
            emoji: e,
            name: n,
            category: *c,
        })
        .collect()
}

const EMOJI_DATA: &[(&str, &str, usize)] = &[
    // Smileys
    ("😀", "grinning", 0),
    ("😃", "smiley", 0),
    ("😄", "smile", 0),
    ("😁", "grin", 0),
    ("😆", "laughing", 0),
    ("😅", "sweat smile", 0),
    ("🤣", "rofl", 0),
    ("😂", "joy", 0),
    ("🙂", "slightly smiling", 0),
    ("🙃", "upside down", 0),
    ("😉", "wink", 0),
    ("😊", "blush", 0),
    ("😇", "innocent", 0),
    ("🥰", "smiling hearts", 0),
    ("😍", "heart eyes", 0),
    ("🤩", "star struck", 0),
    ("😘", "kissing heart", 0),
    ("😋", "yum", 0),
    ("😜", "stuck out tongue winking", 0),
    ("🤪", "zany", 0),
    ("😎", "sunglasses", 0),
    ("🤓", "nerd", 0),
    ("🧐", "monocle", 0),
    ("😏", "smirk", 0),
    ("😒", "unamused", 0),
    ("😞", "disappointed", 0),
    ("😔", "pensive", 0),
    ("😟", "worried", 0),
    ("🙁", "slightly frowning", 0),
    ("😮", "open mouth", 0),
    ("😯", "hushed", 0),
    ("😲", "astonished", 0),
    ("😳", "flushed", 0),
    ("🥺", "pleading", 0),
    ("😢", "cry", 0),
    ("😭", "sob", 0),
    ("😤", "triumph", 0),
    ("😠", "angry", 0),
    ("😡", "rage", 0),
    ("🤬", "cursing", 0),
    ("😈", "smiling imp", 0),
    ("💀", "skull", 0),
    ("💩", "poop", 0),
    ("🤡", "clown", 0),
    ("👻", "ghost", 0),
    ("😱", "scream", 0),
    ("🥶", "cold face", 0),
    ("🥵", "hot face", 0),
    ("🤮", "vomiting", 0),
    ("🤧", "sneezing", 0),
    ("🤠", "cowboy", 0),
    ("🫡", "salute", 0),
    ("🫠", "melting", 0),
    // People
    ("👋", "wave", 1),
    ("🤚", "raised back of hand", 1),
    ("✋", "raised hand", 1),
    ("🖖", "vulcan salute", 1),
    ("👌", "ok hand", 1),
    ("🤌", "pinched fingers", 1),
    ("✌️", "victory", 1),
    ("🤞", "crossed fingers", 1),
    ("🤟", "love you", 1),
    ("🤘", "rock on", 1),
    ("👍", "thumbs up", 1),
    ("👎", "thumbs down", 1),
    ("👏", "clap", 1),
    ("🙌", "raised hands", 1),
    ("🤝", "handshake", 1),
    ("🙏", "pray", 1),
    ("💪", "muscle", 1),
    ("🫶", "heart hands", 1),
    // Nature
    ("🐶", "dog", 2),
    ("🐱", "cat", 2),
    ("🐭", "mouse", 2),
    ("🐰", "rabbit", 2),
    ("🦊", "fox", 2),
    ("🐻", "bear", 2),
    ("🐼", "panda", 2),
    ("🐨", "koala", 2),
    ("🦁", "lion", 2),
    ("🐸", "frog", 2),
    ("🐔", "chicken", 2),
    ("🐧", "penguin", 2),
    ("🦅", "eagle", 2),
    ("🦋", "butterfly", 2),
    ("🌸", "cherry blossom", 2),
    ("🌹", "rose", 2),
    ("🌻", "sunflower", 2),
    ("🌲", "evergreen tree", 2),
    ("🔥", "fire", 2),
    ("🌈", "rainbow", 2),
    ("⭐", "star", 2),
    ("🌙", "crescent moon", 2),
    ("☀️", "sun", 2),
    ("⛈️", "thunder cloud rain", 2),
    // Food
    ("🍎", "apple", 3),
    ("🍕", "pizza", 3),
    ("🍔", "hamburger", 3),
    ("🍟", "fries", 3),
    ("🌮", "taco", 3),
    ("🍣", "sushi", 3),
    ("🍜", "ramen", 3),
    ("🍩", "doughnut", 3),
    ("🍪", "cookie", 3),
    ("🎂", "birthday cake", 3),
    ("🍰", "shortcake", 3),
    ("☕", "coffee", 3),
    ("🧋", "bubble tea", 3),
    ("🍺", "beer", 3),
    ("🍷", "wine", 3),
    // Activities
    ("⚽", "soccer", 4),
    ("🏀", "basketball", 4),
    ("🎮", "video game", 4),
    ("🎯", "dart", 4),
    ("🎲", "dice", 4),
    ("🎸", "guitar", 4),
    ("🎤", "microphone", 4),
    ("🎬", "clapper board", 4),
    ("🎨", "art palette", 4),
    ("🏆", "trophy", 4),
    ("🥇", "gold medal", 4),
    ("🎉", "party popper", 4),
    ("🎊", "confetti ball", 4),
    // Travel
    ("🚗", "car", 5),
    ("✈️", "airplane", 5),
    ("🚀", "rocket", 5),
    ("🏠", "house", 5),
    ("🏖️", "beach", 5),
    ("🗺️", "world map", 5),
    // Objects
    ("💻", "laptop", 6),
    ("📱", "phone", 6),
    ("⌨️", "keyboard", 6),
    ("🖥️", "desktop", 6),
    ("📷", "camera", 6),
    ("💡", "lightbulb", 6),
    ("📝", "memo", 6),
    ("📚", "books", 6),
    ("🔧", "wrench", 6),
    ("🔒", "lock", 6),
    ("🔑", "key", 6),
    // Symbols
    ("❤️", "red heart", 7),
    ("🧡", "orange heart", 7),
    ("💛", "yellow heart", 7),
    ("💚", "green heart", 7),
    ("💙", "blue heart", 7),
    ("💜", "purple heart", 7),
    ("🖤", "black heart", 7),
    ("🤍", "white heart", 7),
    ("💯", "hundred", 7),
    ("✅", "check mark", 7),
    ("❌", "cross mark", 7),
    ("⚠️", "warning", 7),
    ("💬", "speech bubble", 7),
    ("👀", "eyes", 7),
    ("🔴", "red circle", 7),
    ("🟢", "green circle", 7),
];
